import type { Show, Venue, Comedian, Transaction } from './types';

export const comedians: Comedian[] = [
  {
    id: 'com1',
    name: 'John Doe',
    contact: { email: 'john.doe@email.com', phone: '123-456-7890' },
    imageUrl: 'https://placehold.co/100x100.png',
    introSong: 'Eye of the Tiger',
    observations: 'Great with crowd work.',
    performanceHistory: ['show1', 'show3'],
  },
  {
    id: 'com2',
    name: 'Jane Smith',
    contact: { email: 'jane.smith@email.com', phone: '098-765-4321' },
    imageUrl: 'https://placehold.co/100x100.png',
    introSong: 'Crazy Train',
    observations: 'Amazing one-liners.',
    performanceHistory: ['show1', 'show2'],
  },
  {
    id: 'com3',
    name: 'Mike Drop',
    contact: { email: 'mike.drop@email.com', phone: '555-555-5555' },
    imageUrl: 'https://placehold.co/100x100.png',
    introSong: 'Thunderstruck',
    observations: 'Storytelling is top-notch.',
    performanceHistory: ['show2', 'show4'],
  },
   {
    id: 'com4',
    name: 'Alice Giggle',
    contact: { email: 'alice.giggle@email.com', phone: '111-222-3333' },
    imageUrl: 'https://placehold.co/100x100.png',
    introSong: 'Happy',
    observations: 'Charismatic and energetic.',
    performanceHistory: ['show3', 'show4'],
  },
];

export const venues: Venue[] = [
  {
    id: 'ven1',
    name: 'The Laugh Factory',
    address: '123 Comedy Lane, Funnysville',
    contact: { name: 'Manager Mike', email: 'manager@laughfactory.com', phone: '111-111-1111' },
    socialMedia: { twitter: '@laughfactory', instagram: '@laughfactory' },
    imageUrl: 'https://placehold.co/400x200.png',
    availableDays: ['Friday', 'Saturday'],
    showHistory: ['show1', 'show3'],
  },
  {
    id: 'ven2',
    name: 'Comedy Cellar',
    address: '456 Joke Street, Laughtown',
    contact: { name: 'Owner Olivia', email: 'owner@comedycellar.com', phone: '222-222-2222' },
    socialMedia: { twitter: '@comedycellar', instagram: '@comedycellar' },
    imageUrl: 'https://placehold.co/400x200.png',
    availableDays: ['Wednesday', 'Thursday', 'Friday', 'Saturday'],
    showHistory: ['show2', 'show4'],
  },
   {
    id: 'ven3',
    name: 'Giggle Spot',
    address: '789 Chuckle Ave, Smile City',
    contact: { name: 'Booker Ben', email: 'ben@gigglespot.com', phone: '333-333-3333' },
    socialMedia: { twitter: '@gigglespot', instagram: '@gigglespot' },
    imageUrl: 'https://placehold.co/400x200.png',
    availableDays: ['Tuesday', 'Friday', 'Saturday'],
    showHistory: [],
  },
  {
    id: 'ven4',
    name: 'The Stand Up',
    address: '101 Mic Drop Rd, Standupville',
    contact: { name: 'Promoter Pam', email: 'pam@thestandup.com', phone: '444-444-4444' },
    socialMedia: { twitter: '@thestandup', instagram: '@thestandup' },
    imageUrl: 'https://placehold.co/400x200.png',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    showHistory: [],
  },
];

export const shows: Show[] = [
  {
    id: 'show1',
    date: '2024-08-15T20:00:00.000Z',
    location: 'The Laugh Factory',
    lineup: ['John Doe', 'Jane Smith'],
    performers: [comedians[0], comedians[1]],
    notes: 'Sold out show. Great energy.',
    income_expenses_id: 'fin1',
    attendance: 150,
  },
  {
    id: 'show2',
    date: '2024-08-22T21:00:00.000Z',
    location: 'Comedy Cellar',
    lineup: ['Jane Smith', 'Mike Drop'],
    performers: [comedians[1], comedians[2]],
    notes: 'Good turnout, Mike\'s new material killed.',
    income_expenses_id: 'fin2',
    attendance: 120,
  },
  {
    id: 'show3',
    date: '2024-09-05T20:00:00.000Z',
    location: 'The Laugh Factory',
    lineup: ['John Doe', 'Alice Giggle'],
    performers: [comedians[0], comedians[3]],
    notes: 'Upcoming show.',
    income_expenses_id: 'fin3',
    attendance: 0,
  },
  {
    id: 'show4',
    date: '2023-07-20T21:00:00.000Z',
    location: 'Comedy Cellar',
    lineup: ['Mike Drop', 'Alice Giggle'],
    performers: [comedians[2], comedians[3]],
    notes: 'A classic show, full house.',
    income_expenses_id: 'fin4',
    attendance: 135,
  },
];

export const transactions: Transaction[] = [
    { id: 't1', showId: 'show1', date: '2024-08-15T20:00:00.000Z', type: 'income', category: 'ticket sales', amount: 3000, description: 'Ticket sales for Laugh Factory show' },
    { id: 't2', showId: 'show1', date: '2024-08-15T20:00:00.000Z', type: 'expense', category: 'venue rental', amount: 500, description: 'Venue fee' },
    { id: 't3', showId: 'show1', date: '2024-08-15T20:00:00.000Z', type: 'expense', category: 'performer payment', amount: 800, description: 'Payment for John and Jane' },
    { id: 't4', showId: 'show2', date: '2024-08-22T21:00:00.000Z', type: 'income', category: 'ticket sales', amount: 2400, description: 'Ticket sales for Comedy Cellar show' },
    { id: 't5', showId: 'show2', date: '2024-08-22T21:00:00.000Z', type: 'expense', category: 'marketing', amount: 200, description: 'Social media ads' },
    { id: 't6', showId: 'show2', date: '2024-08-22T21:00:00.000Z', type: 'expense', category: 'performer payment', amount: 700, description: 'Payment for performers' },
    { id: 't7', showId: 'show4', date: '2023-07-20T21:00:00.000Z', type: 'income', category: 'ticket sales', amount: 2700, description: 'Ticket sales for classic show' },
    { id: 't8', showId: 'show4', date: '2023-07-20T21:00:00.000Z', type: 'expense', category: 'performer payment', amount: 850, description: 'Payment for Mike and Alice' },
];
